platform :ios, '10.0'
workspace 'UizaSDKExamples'

target 'UizaSDKBasicExample' do
    project 'UizaSDKBasicExample/UizaSDKBasicExample.xcodeproj'
    use_frameworks!
    pod 'UizaSDK'
end

target 'UizaSDKCastingExample' do
    project 'UizaSDKCastingExample/UizaSDKCastingExample.xcodeproj'
    use_frameworks!
    pod 'UizaSDK'
    pod 'google-cast-sdk'
end

target 'UizaSDKGoogleAdsExample' do
    project 'UizaSDKGoogleAdsExample/UizaSDKGoogleAdsExample.xcodeproj'
    use_frameworks!
    pod 'UizaSDK'
    pod 'GoogleAds-IMA-iOS-SDK'
end
